# Generated by Django 5.2.5 on 2025-08-11 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='服务器IP地址或域名', max_length=100, verbose_name='主机地址')),
                ('port', models.IntegerField(default=22, help_text='SSH连接端口，默认22', verbose_name='端口')),
                ('username', models.CharField(help_text='服务器登录用户名', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(help_text='服务器登录密码', max_length=128, verbose_name='密码')),
                ('description', models.TextField(blank=True, help_text='服务器用途或备注信息', verbose_name='描述')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, help_text='记录密码最后一次修改的时间', verbose_name='最后密码修改时间')),
                ('current_duration', models.IntegerField(default=0, help_text='当前密码的有效期，以小时为单位', verbose_name='当前密码有效期（小时）')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'db_table': 'server_info',
                'ordering': ['-last_password_change'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否超级用户')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('otp_secret', models.CharField(blank=True, help_text='用于生成OTP验证码的密钥', max_length=32, null=True, verbose_name='OTP密钥')),
                ('otp_active', models.BooleanField(default=False, help_text='标记用户是否已完成OTP绑定', verbose_name='OTP是否激活')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
