# Generated by Django 5.2.5 on 2025-08-18 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='generated_password',
            field=models.CharField(blank=True, help_text='为用户生成的临时密码', max_length=128, null=True, verbose_name='生成的密码'),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='password_expiration_time',
            field=models.DateTimeField(blank=True, help_text='生成密码的过期时间', null=True, verbose_name='密码过期时间'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录密码最后一次修改的时间', verbose_name='最后密码修改时间'),
        ),
    ]
