# Generated by Django 5.2.5 on 2025-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_serverinfo_generated_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='password',
            field=models.CharField(help_text='服务器登录密码（已加密）', max_length=255, verbose_name='密码'),
        ),
    ]
