# Generated by Django 5.2.5 on 2025-08-26 09:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_serverinfo_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='申请访问的账户名', max_length=50, verbose_name='账户名')),
                ('reason', models.TextField(help_text='申请权限的原因说明', verbose_name='申请原因')),
                ('duration', models.IntegerField(help_text='申请的权限有效期，以小时为单位', verbose_name='申请时长（小时）')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='申请状态')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.serverinfo', verbose_name='目标服务器')),
            ],
            options={
                'verbose_name': '权限申请记录',
                'verbose_name_plural': '权限申请记录',
                'db_table': 'permission_application',
                'ordering': ['-applied_at'],
            },
        ),
    ]
