# Generated by Django 5.2.5 on 2025-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_permissionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionapplication',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, help_text='最后一次OTP验证尝试的时间', null=True, verbose_name='最后验证尝试时间'),
        ),
        migrations.AddField(
            model_name='permissionapplication',
            name='verification_attempts',
            field=models.IntegerField(default=0, help_text='OTP验证尝试次数', verbose_name='验证尝试次数'),
        ),
        migrations.AddField(
            model_name='permissionapplication',
            name='verification_code_sent',
            field=models.BooleanField(default=False, help_text='标记是否已发送OTP验证码', verbose_name='验证码已发送'),
        ),
        migrations.AddField(
            model_name='permissionapplication',
            name='verification_code_sent_at',
            field=models.DateTimeField(blank=True, help_text='OTP验证码发送的时间', null=True, verbose_name='验证码发送时间'),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('verification_pending', '待验证'), ('verification_failed', '验证失败'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=30, verbose_name='申请状态'),
        ),
    ]
