# Generated by Django 5.2.5 on 2025-09-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_permissionapplication_last_verification_attempt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverinfo',
            unique_together={('host', 'username')},
        ),
    ]
