# Generated by Django 5.2.6 on 2025-09-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_serverinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='password_change_type',
            field=models.CharField(choices=[('manual', '手动修改'), ('auto_expired', '自动过期修改'), ('permission_apply', '权限申请修改')], default='manual', help_text='密码修改的类型', max_length=20, verbose_name='密码修改类型'),
        ),
    ]
