# Generated by Django 5.2.6 on 2025-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_serverinfo_password_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionapplication',
            name='maintenance_ticket',
            field=models.CharField(blank=True, help_text='修改操作时的一站式运维单号', max_length=50, null=True, verbose_name='运维单号'),
        ),
        migrations.AddField(
            model_name='permissionapplication',
            name='operation_type',
            field=models.CharField(choices=[('view', '查看'), ('modify', '修改')], default='view', help_text='申请的操作类型：查看或修改', max_length=10, verbose_name='操作类型'),
        ),
    ]
