# Generated by Django 5.2.6 on 2025-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_permissionapplication_maintenance_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionapplication',
            name='batch_hosts',
            field=models.TextField(blank=True, help_text='批量申请时的主机列表，JSON格式存储', null=True, verbose_name='批量申请主机列表'),
        ),
        migrations.AlterField(
            model_name='permissionapplication',
            name='operation_type',
            field=models.CharField(choices=[('view', '查看'), ('modify', '修改'), ('batch_view', '批量查看')], default='view', help_text='申请的操作类型：查看或修改', max_length=10, verbose_name='操作类型'),
        ),
    ]
