# Generated by Django 5.2.6 on 2025-10-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_permissionapplication_batch_hosts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionapplication',
            name='batch_hosts',
        ),
    ]
