# Generated by Django 5.2.6 on 2025-10-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_permissionapplication_batch_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionapplication',
            name='batch_hosts',
            field=models.TextField(blank=True, help_text='批量申请时的主机列表，JSON格式存储', null=True, verbose_name='批量申请主机列表'),
        ),
    ]
